name: 'Run Propolis QA'
description: 'Triggers and polls a test batch using Propolis API'

inputs:
  apiKey:
    description: 'Propolis API Key'
    required: true
  baseUrl:
    description: 'Base URL for the test'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
