name: 'Run Propolis QA'
description: 'Triggers and polls a test batch using Propolis API'

inputs:
  apiKey:
    description: 'Propolis API Key'
    required: true
  baseUrl:
    description: 'Base URL for the test'
    required: false
  nonBlocking:
    description: 'If true, triggers tests without polling for results or affecting build status'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
