name: 'Run Propolis QA'
description: 'Triggers and polls a test batch using Propolis API'

inputs:
  apiKey:
    description: 'Propolis API Key'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
